const OK = 200;
const CREATED = 201;
const ACCEPTED = 202;
const NO_CONTENT = 204;

const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const CONFLICT = 409;
const FORBIDDEN = 403;

const INTERNAL_SERVER_ERROR = 500;
const SERVICE_UNAVAILABLE = 503;

module.exports = {
    BAD_REQUEST,
    UNAUTHORIZED,
    NOT_FOUND,
    CONFLICT,
    OK,
    CREATED,
    ACCEPTED,
    NO_CONTENT,
    INTERNAL_SERVER_ERROR,
    FORBIDDEN,
    SERVICE_UNAVAILABLE
};